// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jin.rooapp13;

import com.jin.rooapp13.MenuSectionFood;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MenuSectionFood_Roo_Configurable {
    
    declare @type: MenuSectionFood: @Configurable;
    
}
