// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jin.rooapp13;

import com.jin.rooapp13.MenuSection;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MenuSection_Roo_Configurable {
    
    declare @type: MenuSection: @Configurable;
    
}
